# Individual homework project 1

In [4]:
# Import modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Import data
customers = pd.read_csv('Data/customers.csv')
transactions = pd.read_csv('Data/transactions.csv')
marketing_campaigns = pd.read_csv('Data/marketing_campaigns.csv')
web_sessions = pd.read_csv('Data/web_sessions.csv')

### Specific questions

Q1. What is the average purchase value for customers from Spain?

In [46]:
df = transactions.merge(customers, on='customer_id', how='left')
avg_purchase_value_spain = df[df["country"] == "Spain"]["purchase_value"].mean()
print(f"Average purchase value for customers in Spain: {avg_purchase_value_spain:.2f} €")

Average purchase value for customers in Spain: 75.63 €

Q2. What is the minimum purchase value for customers from Germany?

In [47]:
df = transactions.merge(customers, on='customer_id')
min_purchase_value_germany = df[df["country"] == "Germany"]["purchase_value"].min()
print(f"Minimum purchase value for customers in Germany: {min_purchase_value_germany:.2f} €")

Minimum purchase value for customers in Germany: 0.39 €

Q3. How much did males spend on buying products in the Sports category?

In [50]:
df = transactions.merge(customers, on='customer_id')
sum_spent_males = df[
    (df["product_category"] == "sports") &
    (df["gender"] == "Male")
]["purchase_value"].sum()
print(f"How much males spend on buying products in the sports category: {sum_spent_males} €")

How much males spend on buying products in the sports category: 191184.72 €

Q4. What is the average age of female customers from Canada?

In [51]:
df = transactions.merge(customers, on='customer_id')
avg_age_f_canada = df[df["country"] == "Canada"]["age"].mean()
print(f"Average age of female customers from Canada: {avg_age_f_canada:.2f} years")

Average age of female customers from Canada: 43.19 years

Q5. How much does an average male customer from the UK spend?

In [45]:
df = transactions.merge(customers, on='customer_id')
sum_spent_males = df[
    (df["country"] == "UK") &
    (df["gender"] == "Male")
]["purchase_value"].mean()
print(f"How much does an average male customer from the UK spend: {sum_spent_males:.2f} €")

How much does an average male customer from the UK spend: 76.63 €

Q6. What is the maximum purchase value for females in the Toys category?

In [52]:
df = transactions.merge(customers, on='customer_id')
max_purchaseValue_f_toys = df[
    (df["product_category"] == "toys") &
    (df["gender"] == "Female")
]["purchase_value"].max()
print(f"What is the maximum purchase value for female toys category: {max_purchaseValue_f_toys} €")

What is the maximum purchase value for female toys category: 423.84 €

Q7. What is the average number of pages viewed for customers who made a purchase (converted)?

In [53]:
web_sessions.head()

,session_id,customer_id,pages_viewed,time_on_site,device_type,traffic_source,session_date,converted
0,1,9716,8,271.238207,desktop,organic,2022-06-18,0
1,2,4617,5,257.386842,mobile,social,2020-07-03,0
2,3,1506,4,289.679888,tablet,paid,2020-12-12,0
3,4,3869,5,146.543376,mobile,direct,2023-09-12,0
4,5,6245,3,339.228209,mobile,email,2019-04-02,0

Q8. What is the average time spent on the site for purchasing vs non-purchasing customers?

In [54]:
marketing_campaigns.head()

,campaign_id,channel,spend,impressions,clicks,conversions,date
0,1,email,32691.17,147741,11333,387,2023-10-22
1,2,display,43333.72,42596,1540,97,2024-03-09
2,3,social,47096.43,22587,1296,111,2022-03-11
3,4,email,18838.78,145817,4609,307,2019-11-04
4,5,paid_search,36828.43,92450,4842,514,2022-03-30

### Visualisation tasks

Q9. Plot purchasing value across years.

Q10. Plot purchasing value across product categories.

### Free exercise

Explore the transactions dataset and:

- Create two visualisations of your choice
- Identify three patterns in the data
- Write five insights in plain English explaining what the data tells us

Your insights should focus on behaviour, spending patterns, or conversion